portal: https://inspire-geoportal.ec.europa.eu/results.html?country=eu&view=details&legislation=all
selenium:
  timeoutmessage: "Timed out waiting for page to load"
  timeouttable: 10
  timeoutrefresh: 5
  timeoutnextpage: 5
  timeoutwaitfordownload: 3
  timeoutnextrequest: 2
  selectors:
    table: "#resultsDataTable"
    select: "select[name='resultsDataTable_length']"
    metadatapage:  "td:nth-child(2) > div > a:nth-child(1)"
    tablerow: "tr"
    metadatapagehref: "href"
    nextpagebutton: "#resultsDataTable_next:not(.disabled)"
    metadatadownload: "#data-metadata-download"
    metadatacountry: "#dataCountry"
    metadatapagedownloadhref: "href"
  datasetperpage: 100
output:
  folder: "data"
request:
  header:
    user_agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.3
    x_mashape_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    connection: keep-alive
  timeout: 30